apiVersion: 1

datasources:
  - name: PostgreSQL - Stocks
    type: postgres
    uid: postgres_stock
    url: postgres:5432
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      database: kraf_db
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
